modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "reeses_sodium_options"

version = "${version}"
displayName = "Reese's Sodium Options"

logoFile="rso-icon.png" #optional

authors="FlashyReese"
# A multi-line description for your mod. This has no minimum length, but it *is* required!
description = '''
Replaces Sodium's Options Screen
'''

[[dependencies.reeses-sodium-options]]
modId="minecraft"
type="required"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "reeses-sodium-options.mixins.json"