name: Self-Hosted runner CI with Gradle

on: [ push ]

jobs:
  build:
    if: github.repository_owner == 'FlashyReese'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build and Publish with Gradle
        run: ./gradlew build publishAllPublicationsToFlashyReeseSnapshotsRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload Auild Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'RSO Artifacts'
          path: build/libs